### ISSUE TITLE
Dark/Light theme switch

### ISSUE THREAD

**Issue by Bengt** [richrace/highlight-line#26]
A setting to switch between light and dark themes as in https://github.com/richrace/highlight-selected would be nice and allow specific color settings. For example using a light theme, I ended up with a "5 % black", which would probably not fit for dark themes:

``` less
.editor {
  .line.highlight-line {
    background: rgba(0, 0, 0, 0.05) !important;
  }
}
```

Here is a screenshot of how that:

![bildschirmfoto von](https://cloud.githubusercontent.com/assets/11575/4346528/e5471d22-4103-11e4-95c1-e871bda03d80.png)
